pages:
  stage: deploy
  image: alpine:3.20
  script:
    - mkdir -p public
    - echo '<!doctype html><meta charset="utf-8"><title>It works</title><h1>🚀 Läuft!</h1><p>Branch: '$CI_COMMIT_BRANCH'</p>' > public/index.html
  artifacts:
    paths: [public]
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/first-init"'
